
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("UserBalance")
export class UserBalance extends AbstractEntity  {

	@Required
	@Column("String")
	id: String

	@Required
	@Column("String")
	account: String

	@Required
	@Column("String")
	market: String

	@Required
	@Column("BigInt")
	lTokenBalance: BigInt

	@Required
	@Column("BigInt")
	borrowBalance: BigInt

	@Required
	@Column("BigInt")
	exchangeRate: BigInt

	@Required
	@Column("String")
	timestamp: String

	@Required
	@Column("String")
	txHash: String

	@Required
	@Column("String")
	trigger: String
  constructor(data: Partial<UserBalance>) {super()}
}


const source = `type UserBalance @entity {
  id: String!
  account: String!
  market: String!
  lTokenBalance: BigInt!
  borrowBalance: BigInt!
  exchangeRate: BigInt!
  timestamp: String!
  txHash: String!
  trigger: String!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "UserBalance": UserBalance
  }
})
