/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
    RocketDepositPoolProcessor,
    RocketTokenRETHProcessor,
    RocketTokenRPLProcessor,
    X2y2Processor,
} from "./types/eth/index.js";

RocketTokenRETHProcessor.bind({
    address: "0xae78736Cd615f374D3085123A210448E74Fc6393",
    network: 1,
})
    .onAllEvents((evt, ctx) => {
        ctx.meter.Counter("event_count").add(1, { name: evt.name });
        ctx.eventLogger.emit(evt.name, {
            ...evt.args.toObject(),
        });
    })
    .onAllTraces(function (trace, ctx) {
        ctx.meter.Counter("trace_count").add(1, { name: trace.name });
        ctx.eventLogger.emit(trace.name, {
            distinctId: trace.action.from,
            ...trace.args.toObject(),
        });
    });

RocketTokenRPLProcessor.bind({
    address: "0xD33526068D116cE69F19A9ee46F0bd304F21A51f",
    network: 1,
})
    .onAllEvents((evt, ctx) => {
        ctx.meter.Counter("event_count").add(1, { name: evt.name });
        ctx.eventLogger.emit(evt.name, {
            ...evt.args.toObject(),
        });
    })
    .onAllTraces(function (trace, ctx) {
        ctx.meter.Counter("trace_count").add(1, { name: trace.name });
        ctx.eventLogger.emit(trace.name, {
            distinctId: trace.action.from,
            ...trace.args.toObject(),
        });
    });

RocketDepositPoolProcessor.bind({
    address: "0x2cac916b2A963Bf162f076C0a8a4a8200BCFBfb4",
    network: 1,
})
    .onAllEvents((evt, ctx) => {
        ctx.meter.Counter("event_count").add(1, { name: evt.name });
        ctx.eventLogger.emit(evt.name, {
            ...evt.args.toObject(),
        });
    })
    .onAllTraces(function (trace, ctx) {
        ctx.meter.Counter("trace_count").add(1, { name: trace.name });
        ctx.eventLogger.emit(trace.name, {
            distinctId: trace.action.from,
            ...trace.args.toObject(),
        });
    });
