
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity, getStore, UpdateValues } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface AccountSnapshotConstructorInput {
  id: ID;
  network: String;
  vault: String;
  account: String;
  timestampMilli: BigInt;
  balance: BigInt;
}
@Entity("AccountSnapshot")
export class AccountSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("String")
	vault: String

	@Required
	@Column("String")
	account: String

	@Required
	@Column("BigInt")
	timestampMilli: BigInt

	@Required
	@Column("BigInt")
	balance: BigInt
  constructor(data: AccountSnapshotConstructorInput) {super()}
  
  
  static update(values: UpdateValues<AccountSnapshotConstructorInput>): Promise<void> {
    return getStore().update(AccountSnapshot, values)
  }
}


interface BeefyAccountSnapshotConstructorInput {
  id: ID;
  network: String;
  vault: String;
  account: String;
  timestampMilli: BigInt;
  balance: BigInt;
}
@Entity("BeefyAccountSnapshot")
export class BeefyAccountSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("String")
	vault: String

	@Required
	@Column("String")
	account: String

	@Required
	@Column("BigInt")
	timestampMilli: BigInt

	@Required
	@Column("BigInt")
	balance: BigInt
  constructor(data: BeefyAccountSnapshotConstructorInput) {super()}
  
  
  static update(values: UpdateValues<BeefyAccountSnapshotConstructorInput>): Promise<void> {
    return getStore().update(BeefyAccountSnapshot, values)
  }
}


const source = `type AccountSnapshot @entity {
  id: ID!
  network: String!
  vault: String!
  account: String!
  timestampMilli: BigInt!
  balance: BigInt!
}

type BeefyAccountSnapshot @entity {
  id: ID!
  network: String!
  vault: String!
  account: String!
  timestampMilli: BigInt!
  balance: BigInt!
}`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot,
		"BeefyAccountSnapshot": BeefyAccountSnapshot
  }
})
