
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity, getStore, UpdateValues } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface BalanceConstructorInput {
  id: ID;
  account: String;
  asset: String;
  balance: BigInt;
}
@Entity("Balance")
export class Balance extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	account: String

	@Required
	@Column("String")
	asset: String

	@Required
	@Column("BigInt")
	balance: BigInt
  constructor(data: BalanceConstructorInput) {super()}
  
  
  static update(values: UpdateValues<BalanceConstructorInput>): Promise<void> {
    return getStore().update(Balance, values)
  }
}


const source = `type Balance @entity {
  id: ID!
  account: String!
  asset: String!
  balance: BigInt!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "Balance": Balance
  }
})
