
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("MarketBasic")
export class MarketBasic extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	contractAddress: String

	@Required
	@Column("BigDecimal")
	baseSupplyIndex: BigDecimal

	@Required
	@Column("BigDecimal")
	baseBorrowIndex: BigDecimal

	@Required
	@Column("BigDecimal")
	totalSupplyBase: BigDecimal

	@Required
	@Column("BigDecimal")
	totalBorrowBase: BigDecimal

	@Required
	@Column("BigDecimal")
	lastAccrualTime: BigDecimal
  constructor(data: Partial<MarketBasic>) {super()}
}

@Entity("UserBasic")
export class UserBasic extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	contractAddress: String

	@Required
	@Column("String")
	address: String

	@Required
	@Column("BigDecimal")
	principal: BigDecimal

	@Required
	@Column("Boolean")
	isNegative: Boolean
  constructor(data: Partial<UserBasic>) {super()}
}

@Entity("MarketConfiguration")
export class MarketConfiguration extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	contractAddress: String

	@Required
	@Column("String")
	baseTokenAddress: String

	@Required
	@Column("Int")
	baseTokenDecimals: Int

	@Required
	@Column("BigDecimal")
	supplyKink: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowKink: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyPerSecondInterestRateBase: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyPerSecondInterestRateSlopeLow: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyPerSecondInterestRateSlopeHigh: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowPerSecondInterestRateBase: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowPerSecondInterestRateSlopeLow: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowPerSecondInterestRateSlopeHigh: BigDecimal
  constructor(data: Partial<MarketConfiguration>) {super()}
}

@Entity("CollateralConfiguration")
export class CollateralConfiguration extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	contractAddress: String

	@Required
	@Column("String")
	assetAddress: String

	@Required
	@Column("Int")
	decimals: Int
  constructor(data: Partial<CollateralConfiguration>) {super()}
}

@Entity("Pool")
export class Pool extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("Int")
	creationBlockNumber: Int

	@Required
	@Column("Int")
	creationTimestamp: Int

	@Required
	@Column("String")
	underlyingTokenAddress: String

	@Required
	@Column("String")
	underlyingTokenSymbol: String

	@Required
	@Column("String")
	receiptTokenAddress: String

	@Required
	@Column("String")
	receiptTokenSymbol: String

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("String")
	poolType: String
  constructor(data: Partial<Pool>) {super()}
}

@Entity("BasePositionSnapshot")
export class BasePositionSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	timestamp: Int

	@Required
	@Column("String")
	blockDate: String

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("String")
	underlyingTokenAddress: String

	@Required
	@Column("String")
	underlyingTokenSymbol: String

	@Required
	@Column("String")
	userAddress: String

	@Required
	@Column("BigDecimal")
	suppliedAmount: BigDecimal

	@Column("BigDecimal")
	suppliedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowedAmount: BigDecimal

	@Column("BigDecimal")
	borrowedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralAmount: BigDecimal

	@Column("BigDecimal")
	collateralAmountUsd?: BigDecimal
  constructor(data: Partial<BasePositionSnapshot>) {super()}
}

@Entity("BasePoolSnapshot")
export class BasePoolSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	timestamp: Int

	@Required
	@Column("String")
	blockDate: String

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("String")
	underlyingTokenAddress: String

	@Required
	@Column("String")
	underlyingTokenSymbol: String

	@Column("BigDecimal")
	underlyingTokenPriceUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	availableAmount: BigDecimal

	@Column("BigDecimal")
	availableAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	suppliedAmount: BigDecimal

	@Column("BigDecimal")
	suppliedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralAmount: BigDecimal

	@Column("BigDecimal")
	collateralAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralFactor: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyIndex: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyApr: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowedAmount: BigDecimal

	@Column("BigDecimal")
	borrowedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowIndex: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowApr: BigDecimal

	@Column("BigDecimal")
	totalFeesUsd?: BigDecimal

	@Column("BigDecimal")
	userFeesUsd?: BigDecimal

	@Column("BigDecimal")
	protocolFeesUsd?: BigDecimal
  constructor(data: Partial<BasePoolSnapshot>) {super()}
}

@Entity("CollateralPosition")
export class CollateralPosition extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("String")
	underlyingTokenAddress: String

	@Required
	@Column("String")
	underlyingTokenSymbol: String

	@Required
	@Column("String")
	userAddress: String

	@Required
	@Column("BigDecimal")
	suppliedAmount: BigDecimal

	@Column("BigDecimal")
	suppliedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowedAmount: BigDecimal

	@Column("BigDecimal")
	borrowedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralAmount: BigDecimal

	@Column("BigDecimal")
	collateralAmountUsd?: BigDecimal
  constructor(data: Partial<CollateralPosition>) {super()}
}

@Entity("CollateralPool")
export class CollateralPool extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("String")
	underlyingTokenAddress: String

	@Required
	@Column("String")
	underlyingTokenSymbol: String

	@Column("BigDecimal")
	underlyingTokenPriceUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	availableAmount: BigDecimal

	@Column("BigDecimal")
	availableAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	suppliedAmount: BigDecimal

	@Column("BigDecimal")
	suppliedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralAmount: BigDecimal

	@Column("BigDecimal")
	collateralAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralFactor: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyIndex: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyApr: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowedAmount: BigDecimal

	@Column("BigDecimal")
	borrowedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowIndex: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowApr: BigDecimal

	@Column("BigDecimal")
	totalFeesUsd?: BigDecimal

	@Column("BigDecimal")
	userFeesUsd?: BigDecimal

	@Column("BigDecimal")
	protocolFeesUsd?: BigDecimal
  constructor(data: Partial<CollateralPool>) {super()}
}

@Entity("CollateralPositionSnapshot")
export class CollateralPositionSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	timestamp: Int

	@Required
	@Column("String")
	blockDate: String

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("String")
	underlyingTokenAddress: String

	@Required
	@Column("String")
	underlyingTokenSymbol: String

	@Required
	@Column("String")
	userAddress: String

	@Required
	@Column("BigDecimal")
	suppliedAmount: BigDecimal

	@Column("BigDecimal")
	suppliedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowedAmount: BigDecimal

	@Column("BigDecimal")
	borrowedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralAmount: BigDecimal

	@Column("BigDecimal")
	collateralAmountUsd?: BigDecimal
  constructor(data: Partial<CollateralPositionSnapshot>) {super()}
}

@Entity("CollateralPoolSnapshot")
export class CollateralPoolSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	timestamp: Int

	@Required
	@Column("String")
	blockDate: String

	@Required
	@Column("Int")
	chainId: Int

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("String")
	underlyingTokenAddress: String

	@Required
	@Column("String")
	underlyingTokenSymbol: String

	@Column("BigDecimal")
	underlyingTokenPriceUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	availableAmount: BigDecimal

	@Column("BigDecimal")
	availableAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	suppliedAmount: BigDecimal

	@Column("BigDecimal")
	suppliedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralAmount: BigDecimal

	@Column("BigDecimal")
	collateralAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	collateralFactor: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyIndex: BigDecimal

	@Required
	@Column("BigDecimal")
	supplyApr: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowedAmount: BigDecimal

	@Column("BigDecimal")
	borrowedAmountUsd?: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowIndex: BigDecimal

	@Required
	@Column("BigDecimal")
	borrowApr: BigDecimal

	@Column("BigDecimal")
	totalFeesUsd?: BigDecimal

	@Column("BigDecimal")
	userFeesUsd?: BigDecimal

	@Column("BigDecimal")
	protocolFeesUsd?: BigDecimal
  constructor(data: Partial<CollateralPoolSnapshot>) {super()}
}


const source = `type MarketBasic @entity {
    id: ID! # Constructed as chainId_marketAddress
    chainId: Int!
    contractAddress: String!
    baseSupplyIndex: BigDecimal!
    baseBorrowIndex: BigDecimal!
    totalSupplyBase: BigDecimal!
    totalBorrowBase: BigDecimal!
    lastAccrualTime: BigDecimal!
}

type UserBasic @entity {
    id: ID!
    chainId: Int!
    contractAddress: String!
    address: String!
    principal: BigDecimal!
    isNegative: Boolean!
}

type MarketConfiguration @entity {
    id: ID!
    chainId: Int!
    contractAddress: String!
    baseTokenAddress: String!
    baseTokenDecimals: Int!
    supplyKink: BigDecimal!
    borrowKink: BigDecimal!
    supplyPerSecondInterestRateBase: BigDecimal!
    supplyPerSecondInterestRateSlopeLow: BigDecimal!
    supplyPerSecondInterestRateSlopeHigh: BigDecimal!
    borrowPerSecondInterestRateBase: BigDecimal!
    borrowPerSecondInterestRateSlopeLow: BigDecimal!
    borrowPerSecondInterestRateSlopeHigh: BigDecimal!
}

type CollateralConfiguration @entity {
    id: ID!
    chainId: Int!
    contractAddress: String!
    assetAddress: String!
    decimals: Int!
}

type Pool @entity {
    id: ID! # Constructed as chainId_poolAddress_underlyingTokenAddress
    chainId: Int!
    creationBlockNumber: Int!
    creationTimestamp: Int!
    underlyingTokenAddress: String! # Address of the underlying token (collateral, base)
    underlyingTokenSymbol: String!
    receiptTokenAddress: String!
    receiptTokenSymbol: String!
    poolAddress: String! # Contract address of the pool (market)
    poolType: String! # collteral_only or supply_only
}

type BasePositionSnapshot @entity {
    id: ID!
    timestamp: Int!
    blockDate: String!
    chainId: Int!
    poolAddress: String!
    underlyingTokenAddress: String!
    underlyingTokenSymbol: String!
    userAddress: String!
    suppliedAmount: BigDecimal!
    suppliedAmountUsd: BigDecimal
    borrowedAmount: BigDecimal!
    borrowedAmountUsd: BigDecimal
    collateralAmount: BigDecimal!
    collateralAmountUsd: BigDecimal
}

type BasePoolSnapshot @entity {
    id: ID!
    timestamp: Int!
    blockDate: String!
    chainId: Int!
    poolAddress: String!
    underlyingTokenAddress: String!
    underlyingTokenSymbol: String!
    underlyingTokenPriceUsd: BigDecimal
    availableAmount: BigDecimal!
    availableAmountUsd: BigDecimal
    suppliedAmount: BigDecimal!
    suppliedAmountUsd: BigDecimal
    collateralAmount: BigDecimal!
    collateralAmountUsd: BigDecimal
    collateralFactor: BigDecimal!
    supplyIndex: BigDecimal!
    supplyApr: BigDecimal!
    borrowedAmount: BigDecimal!
    borrowedAmountUsd: BigDecimal
    borrowIndex: BigDecimal!
    borrowApr: BigDecimal!
    totalFeesUsd: BigDecimal
    userFeesUsd: BigDecimal
    protocolFeesUsd: BigDecimal
}

type CollateralPosition @entity {
    id: ID!
    chainId: Int!
    poolAddress: String!
    underlyingTokenAddress: String!
    underlyingTokenSymbol: String!
    userAddress: String!
    suppliedAmount: BigDecimal!
    suppliedAmountUsd: BigDecimal
    borrowedAmount: BigDecimal!
    borrowedAmountUsd: BigDecimal
    collateralAmount: BigDecimal!
    collateralAmountUsd: BigDecimal
}

type CollateralPool @entity {
    id: ID!
    chainId: Int!
    poolAddress: String!
    underlyingTokenAddress: String!
    underlyingTokenSymbol: String!
    underlyingTokenPriceUsd: BigDecimal
    availableAmount: BigDecimal!
    availableAmountUsd: BigDecimal
    suppliedAmount: BigDecimal!
    suppliedAmountUsd: BigDecimal
    collateralAmount: BigDecimal!
    collateralAmountUsd: BigDecimal
    collateralFactor: BigDecimal!
    supplyIndex: BigDecimal!
    supplyApr: BigDecimal!
    borrowedAmount: BigDecimal!
    borrowedAmountUsd: BigDecimal
    borrowIndex: BigDecimal!
    borrowApr: BigDecimal!
    totalFeesUsd: BigDecimal
    userFeesUsd: BigDecimal
    protocolFeesUsd: BigDecimal
}

type CollateralPositionSnapshot @entity {
    id: ID!
    timestamp: Int!
    blockDate: String!
    chainId: Int!
    poolAddress: String!
    underlyingTokenAddress: String!
    underlyingTokenSymbol: String!
    userAddress: String!
    suppliedAmount: BigDecimal!
    suppliedAmountUsd: BigDecimal
    borrowedAmount: BigDecimal!
    borrowedAmountUsd: BigDecimal
    collateralAmount: BigDecimal!
    collateralAmountUsd: BigDecimal
}

type CollateralPoolSnapshot @entity {
    id: ID!
    timestamp: Int!
    blockDate: String!
    chainId: Int!
    poolAddress: String!
    underlyingTokenAddress: String!
    underlyingTokenSymbol: String!
    underlyingTokenPriceUsd: BigDecimal
    availableAmount: BigDecimal!
    availableAmountUsd: BigDecimal
    suppliedAmount: BigDecimal!
    suppliedAmountUsd: BigDecimal
    collateralAmount: BigDecimal!
    collateralAmountUsd: BigDecimal
    collateralFactor: BigDecimal!
    supplyIndex: BigDecimal!
    supplyApr: BigDecimal!
    borrowedAmount: BigDecimal!
    borrowedAmountUsd: BigDecimal
    borrowIndex: BigDecimal!
    borrowApr: BigDecimal!
    totalFeesUsd: BigDecimal
    userFeesUsd: BigDecimal
    protocolFeesUsd: BigDecimal
}`
DatabaseSchema.register({
  source,
  entities: {
    "MarketBasic": MarketBasic,
		"UserBasic": UserBasic,
		"MarketConfiguration": MarketConfiguration,
		"CollateralConfiguration": CollateralConfiguration,
		"Pool": Pool,
		"BasePositionSnapshot": BasePositionSnapshot,
		"BasePoolSnapshot": BasePoolSnapshot,
		"CollateralPosition": CollateralPosition,
		"CollateralPool": CollateralPool,
		"CollateralPositionSnapshot": CollateralPositionSnapshot,
		"CollateralPoolSnapshot": CollateralPoolSnapshot
  }
})
