
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity, getStore, UpdateValues } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface PositionSnapshotConstructorInput {
  id: ID;
  network: String;
  timestampMilli: BigInt;
  poolAddress: String;
  owner: String;
  stoneBalance: BigInt;
}
@Entity("PositionSnapshot")
export class PositionSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("BigInt")
	timestampMilli: BigInt

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("String")
	owner: String

	@Required
	@Column("BigInt")
	stoneBalance: BigInt
  constructor(data: PositionSnapshotConstructorInput) {super()}
  
  
  static update(values: UpdateValues<PositionSnapshotConstructorInput>): Promise<void> {
    return getStore().update(PositionSnapshot, values)
  }
}


const source = ` type PositionSnapshot @entity {
    id: ID!
    network: String!
    timestampMilli: BigInt!
    poolAddress: String!
    owner: String!
    stoneBalance: BigInt!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "PositionSnapshot": PositionSnapshot
  }
})
