
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("User")
export class User extends AbstractEntity  {

	@Required
	@Column("String")
	id: String
  constructor(data: Partial<User>) {super()}
}


const source = `type User @entity {
  id: String!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "User": User
  }
})
