
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("AccountSnapshot")
export class AccountSnapshot  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	account: String

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("BigInt")
	timestampMilli: BigInt

	@Required
	@Column("BigDecimal")
	stoneBalance: BigDecimal

  constructor(data: Partial<AccountSnapshot>) {}

}


const source = `type AccountSnapshot @entity {
  id: ID!
  account: String!
  poolAddress: String!
  timestampMilli: BigInt!
  stoneBalance: BigDecimal!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot
  }
})
