/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */
import {entity, derivedFrom, DateTime, Int, Float, String, Json, Bytes, ID, Entity, Store} from '@sentio/sdk/store'
import { DatabaseSchema, BigDecimal } from "@sentio/sdk"

type AccountSnapshotData = AccountSnapshot

@entity("AccountSnapshot")
export class AccountSnapshot extends Entity {
  constructor(data: Partial<AccountSnapshotData>) {
    super(data)
  }
	get id(): String { return this.get("id") }
  set id(value: String) { this.set("id", value) }
	get account(): String { return this.get("account") }
  set account(value: String) { this.set("account", value) }
	get timestampMilli(): bigint { return BigInt(this.get("timestampMilli")) }
  set timestampMilli(value: BigInt) { this.set("timestampMilli", value.toString()) }
	get lptBalance(): String { return this.get("lptBalance") }
  set lptBalance(value: String) { this.set("lptBalance", value) }
	get lptSupply(): String { return this.get("lptSupply") }
  set lptSupply(value: String) { this.set("lptSupply", value) }
	get poolInceptionETHBalance(): String { return this.get("poolInceptionETHBalance") }
  set poolInceptionETHBalance(value: String) { this.set("poolInceptionETHBalance", value) }
	get poolWETHBalance(): String { return this.get("poolWETHBalance") }
  set poolWETHBalance(value: String) { this.set("poolWETHBalance", value) }
}

const source = `type AccountSnapshot @entity {
  id: String!
  account: String!
  timestampMilli: BigInt!
  lptBalance: String!
  lptSupply: String!
  poolInceptionETHBalance: String!
  poolWETHBalance: String!
}`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot
  }
})
