
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface AccountSnapshotConstructorInput {
  id: ID;
  lpBalance: BigInt;
  timestampMilli: BigInt;
}
@Entity("AccountSnapshot")
export class AccountSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lpBalance: BigInt

	@Required
	@Column("BigInt")
	timestampMilli: BigInt
  constructor(data: AccountSnapshotConstructorInput) {super()}
}


interface GlobalStateConstructorInput {
  id: ID;
  lpTotalSupply: BigInt;
  totalStoneBalance: BigInt;
}
@Entity("GlobalState")
export class GlobalState extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lpTotalSupply: BigInt

	@Required
	@Column("BigInt")
	totalStoneBalance: BigInt
  constructor(data: GlobalStateConstructorInput) {super()}
}


interface TempEventConstructorInput {
  id: ID;
  eventName: String;
  args: String;
  blockNumber: Int;
  txIdx: Int;
  eventIdx: Int;
  timestampMilli: BigInt;
}
@Entity("TempEvent")
export class TempEvent extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	eventName: String

	@Required
	@Column("String")
	args: String

	@Required
	@Column("Int")
	blockNumber: Int

	@Required
	@Column("Int")
	txIdx: Int

	@Required
	@Column("Int")
	eventIdx: Int

	@Required
	@Column("BigInt")
	timestampMilli: BigInt
  constructor(data: TempEventConstructorInput) {super()}
}


const source = ` type AccountSnapshot @entity {
    id: ID!
    lpBalance: BigInt!
    timestampMilli: BigInt!
}

type GlobalState @entity {
    id: ID!
    lpTotalSupply: BigInt!
    totalStoneBalance: BigInt!
}

type TempEvent @entity {
    id: ID!
    eventName: String!
    args: String!
    blockNumber: Int!
    txIdx: Int!
    eventIdx: Int!
    timestampMilli: BigInt!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot,
		"GlobalState": GlobalState,
		"TempEvent": TempEvent
  }
})
