/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

/* Generated modules for account 0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948 */

import { aptos } from "@sentio/sdk";
import { Address, MoveModule } from "aptos-sdk/src/generated";

export namespace lp_coin {
  export class LP<T0, T1, T2> {
    static TYPE_QNAME =
      "0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948::lp_coin::LP";
    dummy_field: Boolean;
  }

  export function loadTypes(_r: aptos.TypeRegistry) {
    loadAllTypes(_r);
  }
  export const ABI: MoveModule = JSON.parse(
    '{"address":"0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948","name":"lp_coin","friends":[],"exposed_functions":[],"structs":[{"name":"LP","is_native":false,"abilities":[],"generic_type_params":[{"constraints":[]},{"constraints":[]},{"constraints":[]}],"fields":[{"name":"dummy_field","type":"bool"}]}]}'
  );
}

export function loadAllTypes(_r: aptos.TypeRegistry) {
  _r.load(lp_coin.ABI);
}
