
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity, getStore, UpdateValues } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface BalanceConstructorInput {
  id: String;
  blockHeight?: String;
  timestamp: String;
  assetId: String;
  distinctId: String;
  amount: BigInt;
}
@Entity("Balance")
export class Balance extends AbstractEntity  {

	@Required
	@Column("String")
	id: String

	@Column("String")
	blockHeight?: String

	@Required
	@Column("String")
	timestamp: String

	@Required
	@Column("String")
	assetId: String

	@Required
	@Column("String")
	distinctId: String

	@Required
	@Column("BigInt")
	amount: BigInt
  constructor(data: BalanceConstructorInput) {super()}
  
  
  static update(values: UpdateValues<BalanceConstructorInput>): Promise<void> {
    return getStore().update(Balance, values)
  }
}


interface KVConstructorInput {
  id: String;
  value: BigInt;
}
@Entity("KV")
export class KV extends AbstractEntity  {

	@Required
	@Column("String")
	id: String

	@Required
	@Column("BigInt")
	value: BigInt
  constructor(data: KVConstructorInput) {super()}
  
  
  static update(values: UpdateValues<KVConstructorInput>): Promise<void> {
    return getStore().update(KV, values)
  }
}


const source = `type Balance @entity {
  id: String!
  blockHeight: String
  timestamp: String!
  assetId: String!
  distinctId: String!
  amount: BigInt!
}

type KV @entity {
  id: String!
  value: BigInt!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "Balance": Balance,
		"KV": KV
  }
})
