
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("AccountSnapshot")
export class AccountSnapshot extends AbstractEntity  {

	@Required
	@Column("String")
	id: String

	@Required
	@Column("BigInt")
	timestampMilli: BigInt

	@Required
	@Column("BigInt")
	lbtcBalance: BigInt

	@Required
	@Column("BigInt")
	ebtcBalance: BigInt

	@Required
	@Column("BigInt")
	ebtcTotalSupply: BigInt
  constructor(data: Partial<AccountSnapshot>) {super()}
}


const source = `type AccountSnapshot @entity {
  id: String!
  timestampMilli: BigInt!
  lbtcBalance: BigInt!
  ebtcBalance: BigInt!
  ebtcTotalSupply: BigInt!
}`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot
  }
})
