
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("DeriveVaultUserSnapshot")
export class DeriveVaultUserSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	owner: String

	@Required
	@Column("String")
	vaultName: String

	@Required
	@Column("String")
	vaultAddress: String

	@Required
	@Column("BigInt")
	timestampMs: BigInt

	@Required
	@Column("BigDecimal")
	vaultBalance: BigDecimal

	@Required
	@Column("BigDecimal")
	underlyingEffectiveBalance: BigDecimal

	@Required
	@Column("BigDecimal")
	vaultToUnderlying: BigDecimal
  constructor(data: Partial<DeriveVaultUserSnapshot>) {super()}
}

@Entity("DeriveVaultTokenPrice")
export class DeriveVaultTokenPrice extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	vaultAddress: String

	@Required
	@Column("String")
	vaultName: String

	@Required
	@Column("BigInt")
	timestampMs: BigInt

	@Required
	@Column("BigDecimal")
	vaultToUnderlying: BigDecimal
  constructor(data: Partial<DeriveVaultTokenPrice>) {super()}
}


const source = `type DeriveVaultUserSnapshot @entity {
    id: ID!
    owner: String!
    vaultName: String!
    vaultAddress: String!
    timestampMs: BigInt!
    vaultBalance: BigDecimal!
    underlyingEffectiveBalance: BigDecimal!
    vaultToUnderlying: BigDecimal!
}

type DeriveVaultTokenPrice @entity {
    id: ID!
    vaultAddress: String!
    vaultName: String!
    timestampMs: BigInt!
    vaultToUnderlying: BigDecimal!
}`
DatabaseSchema.register({
  source,
  entities: {
    "DeriveVaultUserSnapshot": DeriveVaultUserSnapshot,
		"DeriveVaultTokenPrice": DeriveVaultTokenPrice
  }
})
