
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity, getStore, UpdateValues } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface AccountSnapshotConstructorInput {
  id: ID;
  network: String;
  timestampMilli: BigInt;
  poolAddress: String;
  stoneBalance: BigInt;
}
@Entity("AccountSnapshot")
export class AccountSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("BigInt")
	timestampMilli: BigInt

	@Required
	@Column("String")
	poolAddress: String

	@Required
	@Column("BigInt")
	stoneBalance: BigInt
  constructor(data: AccountSnapshotConstructorInput) {super()}
  
  
  static update(values: UpdateValues<AccountSnapshotConstructorInput>): Promise<void> {
    return getStore().update(AccountSnapshot, values)
  }
}


const source = `type AccountSnapshot @entity {
  id: ID!
  network: String!
  timestampMilli: BigInt!
  poolAddress: String!
  stoneBalance: BigInt!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot
  }
})
