
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity, getStore, UpdateValues } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface AccountSnapshotConstructorInput {
  id: ID;
  network: String;
  timestampMilli: BigInt;
  stoneBalance: BigInt;
}
@Entity("AccountSnapshot")
export class AccountSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("BigInt")
	timestampMilli: BigInt

	@Required
	@Column("BigInt")
	stoneBalance: BigInt
  constructor(data: AccountSnapshotConstructorInput) {super()}
  
  
  static update(values: UpdateValues<AccountSnapshotConstructorInput>): Promise<void> {
    return getStore().update(AccountSnapshot, values)
  }
}


interface TempEventConstructorInput {
  id: ID;
  network: String;
  eventName: String;
  args: String;
  blockNumber: Int;
  txIdx: Int;
  eventIdx: Int;
  timestampMilli: BigInt;
}
@Entity("TempEvent")
export class TempEvent extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("String")
	eventName: String

	@Required
	@Column("String")
	args: String

	@Required
	@Column("Int")
	blockNumber: Int

	@Required
	@Column("Int")
	txIdx: Int

	@Required
	@Column("Int")
	eventIdx: Int

	@Required
	@Column("BigInt")
	timestampMilli: BigInt
  constructor(data: TempEventConstructorInput) {super()}
  
  
  static update(values: UpdateValues<TempEventConstructorInput>): Promise<void> {
    return getStore().update(TempEvent, values)
  }
}


const source = `type AccountSnapshot @entity {
  id: ID!
  network: String!
  timestampMilli: BigInt!
  stoneBalance: BigInt!
}

type TempEvent @entity {
  id: ID!
  network: String!
  eventName: String!
  args: String!
  blockNumber: Int!
  txIdx: Int!
  eventIdx: Int!
  timestampMilli: BigInt!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot,
		"TempEvent": TempEvent
  }
})
