
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity, getStore, UpdateValues } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface AccountSnapshotConstructorInput {
  id: ID;
  network: String;
  balance: BigInt;
  borrowBalance: BigInt;
  netBalance: BigInt;
  timestampMilli: BigInt;
}
@Entity("AccountSnapshot")
export class AccountSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("BigInt")
	balance: BigInt

	@Required
	@Column("BigInt")
	borrowBalance: BigInt

	@Required
	@Column("BigInt")
	netBalance: BigInt

	@Required
	@Column("BigInt")
	timestampMilli: BigInt
  constructor(data: AccountSnapshotConstructorInput) {super()}
  
  
  static update(values: UpdateValues<AccountSnapshotConstructorInput>): Promise<void> {
    return getStore().update(AccountSnapshot, values)
  }
}


interface GlobalStateConstructorInput {
  id: ID;
  network: String;
  exchangeRateRaw: BigInt;
  totalSupply: BigInt;
  totalBorrow: BigInt;
  totalPositiveNetBalance: BigInt;
}
@Entity("GlobalState")
export class GlobalState extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("BigInt")
	exchangeRateRaw: BigInt

	@Required
	@Column("BigInt")
	totalSupply: BigInt

	@Required
	@Column("BigInt")
	totalBorrow: BigInt

	@Required
	@Column("BigInt")
	totalPositiveNetBalance: BigInt
  constructor(data: GlobalStateConstructorInput) {super()}
  
  
  static update(values: UpdateValues<GlobalStateConstructorInput>): Promise<void> {
    return getStore().update(GlobalState, values)
  }
}


interface TempEventConstructorInput {
  id: ID;
  network: String;
  eventName: String;
  args: String;
  blockNumber: Int;
  txIdx: Int;
  eventIdx: Int;
  timestampMilli: BigInt;
}
@Entity("TempEvent")
export class TempEvent extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	network: String

	@Required
	@Column("String")
	eventName: String

	@Required
	@Column("String")
	args: String

	@Required
	@Column("Int")
	blockNumber: Int

	@Required
	@Column("Int")
	txIdx: Int

	@Required
	@Column("Int")
	eventIdx: Int

	@Required
	@Column("BigInt")
	timestampMilli: BigInt
  constructor(data: TempEventConstructorInput) {super()}
  
  
  static update(values: UpdateValues<TempEventConstructorInput>): Promise<void> {
    return getStore().update(TempEvent, values)
  }
}


const source = ` type AccountSnapshot @entity {
    id: ID!
    network: String!
    balance: BigInt!
    borrowBalance: BigInt!
    netBalance: BigInt!
    timestampMilli: BigInt!
}

type GlobalState @entity {
    id: ID!
    network: String!
    exchangeRateRaw: BigInt!
    totalSupply: BigInt!
    totalBorrow: BigInt!
    totalPositiveNetBalance: BigInt!
}

type TempEvent @entity {
    id: ID!
    network: String!
    eventName: String!
    args: String!
    blockNumber: Int!
    txIdx: Int!
    eventIdx: Int!
    timestampMilli: BigInt!
}`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot,
		"GlobalState": GlobalState,
		"TempEvent": TempEvent
  }
})
